### PR TITLE
Update project key to 25 chars

### PR DESCRIPTION
**Pull request by apr-1985**
Fix for.
https://github.com/jfrog/terraform-provider-artifactory/issues/513

### CODE REVIEW

**Comment by apr-1985** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by apr-1985** [comment]
recheck

**Review by alexhung — APPROVED** [review]
Please also update the acceptance test here: https://github.com/jfrog/terraform-provider-project/blob/master/pkg/project/resource_project_test.go#L63

**Comment by apr-1985** [comment]
> Please also update the acceptance test here: https://github.com/jfrog/terraform-provider-project/blob/master/pkg/project/resource_project_test.go#L63

Sorry I looked for tests, didn't realise it was in another project.
Update is here https://github.com/jfrog/terraform-provider-project/pull/48

**Pull request merged**
